"""Offline mock of AlpacaClient — synthetic but internally consistent market.

Purpose: the whole pipeline (signals -> desk -> gates -> execution dry-run ->
journal) must run end-to-end with zero credentials, for tests and for the
`make demo` walkthrough. Prices are generated by the same Black-Scholes the
engine uses, with a volatility smile and configurable spreads, so gate logic
faces realistic numbers.
"""
from __future__ import annotations

import math
import random
from datetime import date, datetime, timedelta, timezone

from ..engine import blackscholes as bs
from ..engine.contracts import occ_symbol


class MockAlpacaClient:
    def __init__(self, *, spot: float = 650.0, atm_iv: float = 0.145,
                 realized_scale: float = 0.80, rel_spread: float = 0.04,
                 seed: int = 7, equity: float = 100_000.0,
                 market_open: bool = True):
        self.spot = spot
        self.atm_iv = atm_iv
        self.realized_scale = realized_scale     # RV = atm_iv * scale (rich vol when < 1)
        self.rel_spread = rel_spread
        self.rng = random.Random(seed)
        self.equity = equity
        self._market_open = market_open
        self.submitted: list[dict] = []

    # -- trading ----------------------------------------------------------
    def account(self) -> dict:
        return {"id": "MOCK-ACCT", "equity": str(self.equity),
                "last_equity": str(self.equity), "buying_power": str(self.equity * 2),
                "options_approved_level": 3, "options_trading_level": 3}

    def clock(self) -> dict:
        now = datetime.now(timezone.utc)
        return {"timestamp": now.isoformat(), "is_open": self._market_open,
                "next_open": now.isoformat(), "next_close": (now + timedelta(hours=3)).isoformat()}

    def positions(self) -> list[dict]:
        return []

    def orders(self, status: str = "all", limit: int = 200) -> list[dict]:
        return self.submitted

    def submit_order(self, payload: dict) -> dict:
        oid = f"mock-{len(self.submitted) + 1:04d}"
        rec = dict(payload)
        rec.update({"id": oid, "status": "accepted"})
        self.submitted.append(rec)
        return rec

    def cancel_order(self, order_id: str) -> None:
        pass

    def order_by_client_id(self, client_order_id: str) -> dict | None:
        for o in self.submitted:
            if o.get("client_order_id") == client_order_id:
                return {**o, "status": "filled", "filled_avg_price": o.get("limit_price")}
        return None

    def portfolio_history(self, period: str = "1M", timeframe: str = "1D") -> dict:
        return {"equity": [self.equity], "timestamp": [int(datetime.now(timezone.utc).timestamp())]}

    def activities(self, activity_type: str | None = None) -> list[dict]:
        return []

    # -- market data ------------------------------------------------------
    def _smile_iv(self, strike: float) -> float:
        # simple put-skewed smile around spot
        m = math.log(strike / self.spot)
        return max(0.07, self.atm_iv + (-0.35 * m) + 0.55 * m * m)

    def option_chain(self, underlying: str, expiry: str, feed: str = "indicative") -> dict[str, dict]:
        exp = date.fromisoformat(expiry)
        now = datetime.now(timezone.utc)
        t = max(1e-6, (datetime(exp.year, exp.month, exp.day, 20, tzinfo=timezone.utc)
                       - now).total_seconds() / (365 * 86400))
        out: dict[str, dict] = {}
        lo = int(self.spot * 0.80 // 5 * 5)
        hi = int(self.spot * 1.20 // 5 * 5) + 5
        for strike in range(lo, hi, 5):
            iv = self._smile_iv(float(strike))
            for right in ("C", "P"):
                mid = bs.price(self.spot, strike, t, iv, right)
                if mid < 0.03:
                    continue
                half = max(0.01, mid * self.rel_spread / 2)
                g = bs.greeks(self.spot, strike, t, iv, right)
                sym = occ_symbol(underlying, exp, right, float(strike))
                out[sym] = {
                    "latestQuote": {"bp": round(mid - half, 2), "ap": round(mid + half, 2),
                                    "bs": 10, "as": 10, "t": now.isoformat()},
                    # vega in Alpaca's convention: per share per 1 vol POINT
                    "greeks": {"delta": round(g.delta, 4), "gamma": round(g.gamma, 6),
                               "theta": round(g.theta, 4), "vega": round(g.vega / 100.0, 4),
                               "rho": round(g.rho, 4)},
                    "impliedVolatility": round(iv, 4),
                }
        return out

    def stock_bars_daily(self, symbol: str, days: int = 40,
                         exclude_date: str | None = None) -> list[dict]:
        """Deterministic path with alternating +/-sigma daily log-returns, so
        realized vol == atm_iv * realized_scale exactly (up to the n/(n-1)
        sample factor). Random walks with a 20-point lookback were too noisy
        to test regime branches reliably — see DEVLOG. Bars are the last
        `days` weekdays ending YESTERDAY, like the fixed live client."""
        daily_sigma = self.atm_iv * self.realized_scale / math.sqrt(252)
        px = self.spot
        rets = []
        for i in range(days):
            rets.append(daily_sigma if i % 2 == 0 else -daily_sigma)
        closes = []
        for r in reversed(rets):
            closes.append(px)
            px /= math.exp(r)
        closes.reverse()
        scale = self.spot / closes[-1]
        # the last `days` weekdays ending yesterday (today's bar is in progress
        # and excluded by the live client too)
        dates = []
        d = datetime.now(timezone.utc) - timedelta(days=1)
        while len(dates) < days:
            if d.weekday() < 5:
                dates.append(d)
            d -= timedelta(days=1)
        dates.reverse()
        bars = []
        for i, d in enumerate(dates):
            c = closes[i] * scale
            bars.append({"t": d.strftime("%Y-%m-%dT04:00:00Z"), "o": c, "h": c, "l": c,
                         "c": round(c, 4), "v": 1_000_000})
        if exclude_date:
            bars = [b for b in bars if b["t"][:10] < exclude_date]
        return bars

    def latest_stock_quote(self, symbol: str) -> dict:
        return {"bp": self.spot - 0.01, "ap": self.spot + 0.01}

    def news(self, symbols: str = "SPY", limit: int = 12) -> list[dict]:
        return [{"headline": "Markets quiet ahead of next week's data", "created_at":
                 datetime.now(timezone.utc).isoformat(), "source": "mock"}]
